#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevERP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DevERP")]
	public partial class DevERPDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_DailyStock(tbl_DailyStock instance);
    partial void Updatetbl_DailyStock(tbl_DailyStock instance);
    partial void Deletetbl_DailyStock(tbl_DailyStock instance);
    partial void Inserttbl_EmployeeEntry(tbl_EmployeeEntry instance);
    partial void Updatetbl_EmployeeEntry(tbl_EmployeeEntry instance);
    partial void Deletetbl_EmployeeEntry(tbl_EmployeeEntry instance);
    partial void Inserttbl_ProductionDeleteHistory(tbl_ProductionDeleteHistory instance);
    partial void Updatetbl_ProductionDeleteHistory(tbl_ProductionDeleteHistory instance);
    partial void Deletetbl_ProductionDeleteHistory(tbl_ProductionDeleteHistory instance);
    partial void Inserttbl_ProductionInfo(tbl_ProductionInfo instance);
    partial void Updatetbl_ProductionInfo(tbl_ProductionInfo instance);
    partial void Deletetbl_ProductionInfo(tbl_ProductionInfo instance);
    partial void Inserttbl_ProductName(tbl_ProductName instance);
    partial void Updatetbl_ProductName(tbl_ProductName instance);
    partial void Deletetbl_ProductName(tbl_ProductName instance);
    partial void Inserttbl_ProductSize(tbl_ProductSize instance);
    partial void Updatetbl_ProductSize(tbl_ProductSize instance);
    partial void Deletetbl_ProductSize(tbl_ProductSize instance);
    partial void Inserttbl_ProductType(tbl_ProductType instance);
    partial void Updatetbl_ProductType(tbl_ProductType instance);
    partial void Deletetbl_ProductType(tbl_ProductType instance);
    partial void Inserttbl_Stock(tbl_Stock instance);
    partial void Updatetbl_Stock(tbl_Stock instance);
    partial void Deletetbl_Stock(tbl_Stock instance);
    #endregion
		
		public DevERPDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Connection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DevERPDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DevERPDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DevERPDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DevERPDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_DailyStock> tbl_DailyStocks
		{
			get
			{
				return this.GetTable<tbl_DailyStock>();
			}
		}
		
		public System.Data.Linq.Table<tbl_EmployeeEntry> tbl_EmployeeEntries
		{
			get
			{
				return this.GetTable<tbl_EmployeeEntry>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ProductionDeleteHistory> tbl_ProductionDeleteHistories
		{
			get
			{
				return this.GetTable<tbl_ProductionDeleteHistory>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ProductionInfo> tbl_ProductionInfos
		{
			get
			{
				return this.GetTable<tbl_ProductionInfo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ProductName> tbl_ProductNames
		{
			get
			{
				return this.GetTable<tbl_ProductName>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ProductSize> tbl_ProductSizes
		{
			get
			{
				return this.GetTable<tbl_ProductSize>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ProductType> tbl_ProductTypes
		{
			get
			{
				return this.GetTable<tbl_ProductType>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Stock> tbl_Stocks
		{
			get
			{
				return this.GetTable<tbl_Stock>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DailyStock")]
	public partial class tbl_DailyStock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<System.DateTime> _RecordDate;
		
		private System.Nullable<int> _ProductId;
		
		private System.Nullable<double> _PreviousQuantity;
		
		private System.Nullable<double> _DailyProduction;
		
		private System.Nullable<double> _DailySell;
		
		private System.Nullable<double> _BalanceQty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnRecordDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRecordDateChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnPreviousQuantityChanging(System.Nullable<double> value);
    partial void OnPreviousQuantityChanged();
    partial void OnDailyProductionChanging(System.Nullable<double> value);
    partial void OnDailyProductionChanged();
    partial void OnDailySellChanging(System.Nullable<double> value);
    partial void OnDailySellChanged();
    partial void OnBalanceQtyChanging(System.Nullable<double> value);
    partial void OnBalanceQtyChanged();
    #endregion
		
		public tbl_DailyStock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordDate", DbType="Date")]
		public System.Nullable<System.DateTime> RecordDate
		{
			get
			{
				return this._RecordDate;
			}
			set
			{
				if ((this._RecordDate != value))
				{
					this.OnRecordDateChanging(value);
					this.SendPropertyChanging();
					this._RecordDate = value;
					this.SendPropertyChanged("RecordDate");
					this.OnRecordDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousQuantity", DbType="Float")]
		public System.Nullable<double> PreviousQuantity
		{
			get
			{
				return this._PreviousQuantity;
			}
			set
			{
				if ((this._PreviousQuantity != value))
				{
					this.OnPreviousQuantityChanging(value);
					this.SendPropertyChanging();
					this._PreviousQuantity = value;
					this.SendPropertyChanged("PreviousQuantity");
					this.OnPreviousQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DailyProduction", DbType="Float")]
		public System.Nullable<double> DailyProduction
		{
			get
			{
				return this._DailyProduction;
			}
			set
			{
				if ((this._DailyProduction != value))
				{
					this.OnDailyProductionChanging(value);
					this.SendPropertyChanging();
					this._DailyProduction = value;
					this.SendPropertyChanged("DailyProduction");
					this.OnDailyProductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DailySell", DbType="Float")]
		public System.Nullable<double> DailySell
		{
			get
			{
				return this._DailySell;
			}
			set
			{
				if ((this._DailySell != value))
				{
					this.OnDailySellChanging(value);
					this.SendPropertyChanging();
					this._DailySell = value;
					this.SendPropertyChanged("DailySell");
					this.OnDailySellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceQty", DbType="Float")]
		public System.Nullable<double> BalanceQty
		{
			get
			{
				return this._BalanceQty;
			}
			set
			{
				if ((this._BalanceQty != value))
				{
					this.OnBalanceQtyChanging(value);
					this.SendPropertyChanging();
					this._BalanceQty = value;
					this.SendPropertyChanged("BalanceQty");
					this.OnBalanceQtyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_EmployeeEntry")]
	public partial class tbl_EmployeeEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmpId;
		
		private string _EmployeeId;
		
		private string _EmployeeIdBangla;
		
		private string _DepartmentId;
		
		private int _DesignationId;
		
		private System.Nullable<int> _Grade;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _FirstNameBangla;
		
		private string _LastNameBangla;
		
		private string _ShortName;
		
		private string _AdditionalId;
		
		private string _FatherName;
		
		private string _MotherName;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private string _PlaceOfBirth;
		
		private string _Gender;
		
		private string _BloodGroup;
		
		private string _Nationality;
		
		private string _NationalIdCardNo;
		
		private string _NationalIdCardNoBangla;
		
		private string _Religion;
		
		private string _Hobbies;
		
		private string _MaritialStatus;
		
		private System.Nullable<System.DateTime> _MarriageDate;
		
		private string _PresentAddress;
		
		private string _ParmanentAddress;
		
		private string _ParmanentAddressBangla;
		
		private string _OfficialPhone;
		
		private string _PersonalPhone;
		
		private string _OfficialEmail;
		
		private string _PersonalEmail;
		
		private System.Nullable<int> _UserId;
		
		private string _AttendenceCardId;
		
		private string _AttendenceCardIdBangla;
		
		private string _FingerPrintId;
		
		private System.Data.Linq.Binary _EmployeePicture;
		
		private System.Data.Linq.Binary _DigitalSignature;
		
		private int _GrossSalary;
		
		private System.Nullable<int> _BasicSalary;
		
		private System.Nullable<int> _HouseRent;
		
		private System.Nullable<int> _MedicalSupport;
		
		private System.Nullable<int> _ConvanceSupport;
		
		private System.Nullable<int> _FoodSupport;
		
		private System.Nullable<double> _OverTimeRate;
		
		private System.Nullable<System.DateTime> _JoiningDate;
		
		private string _JoiningDateBangla;
		
		private System.Nullable<int> _LineId;
		
		private System.Nullable<int> _CatagoryId;
		
		private System.Nullable<System.DateTime> _EntryOrDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpIdChanging(int value);
    partial void OnEmpIdChanged();
    partial void OnEmployeeIdChanging(string value);
    partial void OnEmployeeIdChanged();
    partial void OnEmployeeIdBanglaChanging(string value);
    partial void OnEmployeeIdBanglaChanged();
    partial void OnDepartmentIdChanging(string value);
    partial void OnDepartmentIdChanged();
    partial void OnDesignationIdChanging(int value);
    partial void OnDesignationIdChanged();
    partial void OnGradeChanging(System.Nullable<int> value);
    partial void OnGradeChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameBanglaChanging(string value);
    partial void OnFirstNameBanglaChanged();
    partial void OnLastNameBanglaChanging(string value);
    partial void OnLastNameBanglaChanged();
    partial void OnShortNameChanging(string value);
    partial void OnShortNameChanged();
    partial void OnAdditionalIdChanging(string value);
    partial void OnAdditionalIdChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnMotherNameChanging(string value);
    partial void OnMotherNameChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnPlaceOfBirthChanging(string value);
    partial void OnPlaceOfBirthChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnBloodGroupChanging(string value);
    partial void OnBloodGroupChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnNationalIdCardNoChanging(string value);
    partial void OnNationalIdCardNoChanged();
    partial void OnNationalIdCardNoBanglaChanging(string value);
    partial void OnNationalIdCardNoBanglaChanged();
    partial void OnReligionChanging(string value);
    partial void OnReligionChanged();
    partial void OnHobbiesChanging(string value);
    partial void OnHobbiesChanged();
    partial void OnMaritialStatusChanging(string value);
    partial void OnMaritialStatusChanged();
    partial void OnMarriageDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMarriageDateChanged();
    partial void OnPresentAddressChanging(string value);
    partial void OnPresentAddressChanged();
    partial void OnParmanentAddressChanging(string value);
    partial void OnParmanentAddressChanged();
    partial void OnParmanentAddressBanglaChanging(string value);
    partial void OnParmanentAddressBanglaChanged();
    partial void OnOfficialPhoneChanging(string value);
    partial void OnOfficialPhoneChanged();
    partial void OnPersonalPhoneChanging(string value);
    partial void OnPersonalPhoneChanged();
    partial void OnOfficialEmailChanging(string value);
    partial void OnOfficialEmailChanged();
    partial void OnPersonalEmailChanging(string value);
    partial void OnPersonalEmailChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnAttendenceCardIdChanging(string value);
    partial void OnAttendenceCardIdChanged();
    partial void OnAttendenceCardIdBanglaChanging(string value);
    partial void OnAttendenceCardIdBanglaChanged();
    partial void OnFingerPrintIdChanging(string value);
    partial void OnFingerPrintIdChanged();
    partial void OnEmployeePictureChanging(System.Data.Linq.Binary value);
    partial void OnEmployeePictureChanged();
    partial void OnDigitalSignatureChanging(System.Data.Linq.Binary value);
    partial void OnDigitalSignatureChanged();
    partial void OnGrossSalaryChanging(int value);
    partial void OnGrossSalaryChanged();
    partial void OnBasicSalaryChanging(System.Nullable<int> value);
    partial void OnBasicSalaryChanged();
    partial void OnHouseRentChanging(System.Nullable<int> value);
    partial void OnHouseRentChanged();
    partial void OnMedicalSupportChanging(System.Nullable<int> value);
    partial void OnMedicalSupportChanged();
    partial void OnConvanceSupportChanging(System.Nullable<int> value);
    partial void OnConvanceSupportChanged();
    partial void OnFoodSupportChanging(System.Nullable<int> value);
    partial void OnFoodSupportChanged();
    partial void OnOverTimeRateChanging(System.Nullable<double> value);
    partial void OnOverTimeRateChanged();
    partial void OnJoiningDateChanging(System.Nullable<System.DateTime> value);
    partial void OnJoiningDateChanged();
    partial void OnJoiningDateBanglaChanging(string value);
    partial void OnJoiningDateBanglaChanged();
    partial void OnLineIdChanging(System.Nullable<int> value);
    partial void OnLineIdChanged();
    partial void OnCatagoryIdChanging(System.Nullable<int> value);
    partial void OnCatagoryIdChanged();
    partial void OnEntryOrDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEntryOrDateChanged();
    #endregion
		
		public tbl_EmployeeEntry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this.OnEmpIdChanging(value);
					this.SendPropertyChanging();
					this._EmpId = value;
					this.SendPropertyChanged("EmpId");
					this.OnEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeIdBangla", DbType="NChar(50)")]
		public string EmployeeIdBangla
		{
			get
			{
				return this._EmployeeIdBangla;
			}
			set
			{
				if ((this._EmployeeIdBangla != value))
				{
					this.OnEmployeeIdBanglaChanging(value);
					this.SendPropertyChanging();
					this._EmployeeIdBangla = value;
					this.SendPropertyChanged("EmployeeIdBangla");
					this.OnEmployeeIdBanglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DepartmentId
		{
			get
			{
				return this._DepartmentId;
			}
			set
			{
				if ((this._DepartmentId != value))
				{
					this.OnDepartmentIdChanging(value);
					this.SendPropertyChanging();
					this._DepartmentId = value;
					this.SendPropertyChanged("DepartmentId");
					this.OnDepartmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DesignationId", DbType="Int NOT NULL")]
		public int DesignationId
		{
			get
			{
				return this._DesignationId;
			}
			set
			{
				if ((this._DesignationId != value))
				{
					this.OnDesignationIdChanging(value);
					this.SendPropertyChanging();
					this._DesignationId = value;
					this.SendPropertyChanged("DesignationId");
					this.OnDesignationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Int")]
		public System.Nullable<int> Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this.OnGradeChanging(value);
					this.SendPropertyChanging();
					this._Grade = value;
					this.SendPropertyChanged("Grade");
					this.OnGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstNameBangla", DbType="NChar(500)")]
		public string FirstNameBangla
		{
			get
			{
				return this._FirstNameBangla;
			}
			set
			{
				if ((this._FirstNameBangla != value))
				{
					this.OnFirstNameBanglaChanging(value);
					this.SendPropertyChanging();
					this._FirstNameBangla = value;
					this.SendPropertyChanged("FirstNameBangla");
					this.OnFirstNameBanglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNameBangla", DbType="NChar(500)")]
		public string LastNameBangla
		{
			get
			{
				return this._LastNameBangla;
			}
			set
			{
				if ((this._LastNameBangla != value))
				{
					this.OnLastNameBanglaChanging(value);
					this.SendPropertyChanging();
					this._LastNameBangla = value;
					this.SendPropertyChanged("LastNameBangla");
					this.OnLastNameBanglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="VarChar(50)")]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this.OnShortNameChanging(value);
					this.SendPropertyChanging();
					this._ShortName = value;
					this.SendPropertyChanged("ShortName");
					this.OnShortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalId", DbType="VarChar(50)")]
		public string AdditionalId
		{
			get
			{
				return this._AdditionalId;
			}
			set
			{
				if ((this._AdditionalId != value))
				{
					this.OnAdditionalIdChanging(value);
					this.SendPropertyChanging();
					this._AdditionalId = value;
					this.SendPropertyChanged("AdditionalId");
					this.OnAdditionalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="VarChar(100)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="VarChar(100)")]
		public string MotherName
		{
			get
			{
				return this._MotherName;
			}
			set
			{
				if ((this._MotherName != value))
				{
					this.OnMotherNameChanging(value);
					this.SendPropertyChanging();
					this._MotherName = value;
					this.SendPropertyChanged("MotherName");
					this.OnMotherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceOfBirth", DbType="VarChar(100)")]
		public string PlaceOfBirth
		{
			get
			{
				return this._PlaceOfBirth;
			}
			set
			{
				if ((this._PlaceOfBirth != value))
				{
					this.OnPlaceOfBirthChanging(value);
					this.SendPropertyChanging();
					this._PlaceOfBirth = value;
					this.SendPropertyChanged("PlaceOfBirth");
					this.OnPlaceOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodGroup", DbType="VarChar(3)")]
		public string BloodGroup
		{
			get
			{
				return this._BloodGroup;
			}
			set
			{
				if ((this._BloodGroup != value))
				{
					this.OnBloodGroupChanging(value);
					this.SendPropertyChanging();
					this._BloodGroup = value;
					this.SendPropertyChanged("BloodGroup");
					this.OnBloodGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(20)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalIdCardNo", DbType="VarChar(20)")]
		public string NationalIdCardNo
		{
			get
			{
				return this._NationalIdCardNo;
			}
			set
			{
				if ((this._NationalIdCardNo != value))
				{
					this.OnNationalIdCardNoChanging(value);
					this.SendPropertyChanging();
					this._NationalIdCardNo = value;
					this.SendPropertyChanged("NationalIdCardNo");
					this.OnNationalIdCardNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalIdCardNoBangla", DbType="NChar(200)")]
		public string NationalIdCardNoBangla
		{
			get
			{
				return this._NationalIdCardNoBangla;
			}
			set
			{
				if ((this._NationalIdCardNoBangla != value))
				{
					this.OnNationalIdCardNoBanglaChanging(value);
					this.SendPropertyChanging();
					this._NationalIdCardNoBangla = value;
					this.SendPropertyChanged("NationalIdCardNoBangla");
					this.OnNationalIdCardNoBanglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="VarChar(10)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this.OnReligionChanging(value);
					this.SendPropertyChanging();
					this._Religion = value;
					this.SendPropertyChanged("Religion");
					this.OnReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hobbies", DbType="VarChar(MAX)")]
		public string Hobbies
		{
			get
			{
				return this._Hobbies;
			}
			set
			{
				if ((this._Hobbies != value))
				{
					this.OnHobbiesChanging(value);
					this.SendPropertyChanging();
					this._Hobbies = value;
					this.SendPropertyChanged("Hobbies");
					this.OnHobbiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritialStatus", DbType="VarChar(20)")]
		public string MaritialStatus
		{
			get
			{
				return this._MaritialStatus;
			}
			set
			{
				if ((this._MaritialStatus != value))
				{
					this.OnMaritialStatusChanging(value);
					this.SendPropertyChanging();
					this._MaritialStatus = value;
					this.SendPropertyChanged("MaritialStatus");
					this.OnMaritialStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarriageDate", DbType="Date")]
		public System.Nullable<System.DateTime> MarriageDate
		{
			get
			{
				return this._MarriageDate;
			}
			set
			{
				if ((this._MarriageDate != value))
				{
					this.OnMarriageDateChanging(value);
					this.SendPropertyChanging();
					this._MarriageDate = value;
					this.SendPropertyChanged("MarriageDate");
					this.OnMarriageDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentAddress", DbType="VarChar(MAX)")]
		public string PresentAddress
		{
			get
			{
				return this._PresentAddress;
			}
			set
			{
				if ((this._PresentAddress != value))
				{
					this.OnPresentAddressChanging(value);
					this.SendPropertyChanging();
					this._PresentAddress = value;
					this.SendPropertyChanged("PresentAddress");
					this.OnPresentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmanentAddress", DbType="VarChar(MAX)")]
		public string ParmanentAddress
		{
			get
			{
				return this._ParmanentAddress;
			}
			set
			{
				if ((this._ParmanentAddress != value))
				{
					this.OnParmanentAddressChanging(value);
					this.SendPropertyChanging();
					this._ParmanentAddress = value;
					this.SendPropertyChanged("ParmanentAddress");
					this.OnParmanentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmanentAddressBangla", DbType="NChar(1000)")]
		public string ParmanentAddressBangla
		{
			get
			{
				return this._ParmanentAddressBangla;
			}
			set
			{
				if ((this._ParmanentAddressBangla != value))
				{
					this.OnParmanentAddressBanglaChanging(value);
					this.SendPropertyChanging();
					this._ParmanentAddressBangla = value;
					this.SendPropertyChanged("ParmanentAddressBangla");
					this.OnParmanentAddressBanglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficialPhone", DbType="VarChar(15)")]
		public string OfficialPhone
		{
			get
			{
				return this._OfficialPhone;
			}
			set
			{
				if ((this._OfficialPhone != value))
				{
					this.OnOfficialPhoneChanging(value);
					this.SendPropertyChanging();
					this._OfficialPhone = value;
					this.SendPropertyChanged("OfficialPhone");
					this.OnOfficialPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalPhone", DbType="VarChar(15)")]
		public string PersonalPhone
		{
			get
			{
				return this._PersonalPhone;
			}
			set
			{
				if ((this._PersonalPhone != value))
				{
					this.OnPersonalPhoneChanging(value);
					this.SendPropertyChanging();
					this._PersonalPhone = value;
					this.SendPropertyChanged("PersonalPhone");
					this.OnPersonalPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficialEmail", DbType="VarChar(320)")]
		public string OfficialEmail
		{
			get
			{
				return this._OfficialEmail;
			}
			set
			{
				if ((this._OfficialEmail != value))
				{
					this.OnOfficialEmailChanging(value);
					this.SendPropertyChanging();
					this._OfficialEmail = value;
					this.SendPropertyChanged("OfficialEmail");
					this.OnOfficialEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonalEmail", DbType="VarChar(320)")]
		public string PersonalEmail
		{
			get
			{
				return this._PersonalEmail;
			}
			set
			{
				if ((this._PersonalEmail != value))
				{
					this.OnPersonalEmailChanging(value);
					this.SendPropertyChanging();
					this._PersonalEmail = value;
					this.SendPropertyChanged("PersonalEmail");
					this.OnPersonalEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendenceCardId", DbType="VarChar(50)")]
		public string AttendenceCardId
		{
			get
			{
				return this._AttendenceCardId;
			}
			set
			{
				if ((this._AttendenceCardId != value))
				{
					this.OnAttendenceCardIdChanging(value);
					this.SendPropertyChanging();
					this._AttendenceCardId = value;
					this.SendPropertyChanged("AttendenceCardId");
					this.OnAttendenceCardIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendenceCardIdBangla", DbType="NChar(50)")]
		public string AttendenceCardIdBangla
		{
			get
			{
				return this._AttendenceCardIdBangla;
			}
			set
			{
				if ((this._AttendenceCardIdBangla != value))
				{
					this.OnAttendenceCardIdBanglaChanging(value);
					this.SendPropertyChanging();
					this._AttendenceCardIdBangla = value;
					this.SendPropertyChanged("AttendenceCardIdBangla");
					this.OnAttendenceCardIdBanglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FingerPrintId", DbType="VarChar(50)")]
		public string FingerPrintId
		{
			get
			{
				return this._FingerPrintId;
			}
			set
			{
				if ((this._FingerPrintId != value))
				{
					this.OnFingerPrintIdChanging(value);
					this.SendPropertyChanging();
					this._FingerPrintId = value;
					this.SendPropertyChanged("FingerPrintId");
					this.OnFingerPrintIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeePicture", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary EmployeePicture
		{
			get
			{
				return this._EmployeePicture;
			}
			set
			{
				if ((this._EmployeePicture != value))
				{
					this.OnEmployeePictureChanging(value);
					this.SendPropertyChanging();
					this._EmployeePicture = value;
					this.SendPropertyChanged("EmployeePicture");
					this.OnEmployeePictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DigitalSignature", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary DigitalSignature
		{
			get
			{
				return this._DigitalSignature;
			}
			set
			{
				if ((this._DigitalSignature != value))
				{
					this.OnDigitalSignatureChanging(value);
					this.SendPropertyChanging();
					this._DigitalSignature = value;
					this.SendPropertyChanged("DigitalSignature");
					this.OnDigitalSignatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrossSalary", DbType="Int NOT NULL")]
		public int GrossSalary
		{
			get
			{
				return this._GrossSalary;
			}
			set
			{
				if ((this._GrossSalary != value))
				{
					this.OnGrossSalaryChanging(value);
					this.SendPropertyChanging();
					this._GrossSalary = value;
					this.SendPropertyChanged("GrossSalary");
					this.OnGrossSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSalary", DbType="Int")]
		public System.Nullable<int> BasicSalary
		{
			get
			{
				return this._BasicSalary;
			}
			set
			{
				if ((this._BasicSalary != value))
				{
					this.OnBasicSalaryChanging(value);
					this.SendPropertyChanging();
					this._BasicSalary = value;
					this.SendPropertyChanged("BasicSalary");
					this.OnBasicSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseRent", DbType="Int")]
		public System.Nullable<int> HouseRent
		{
			get
			{
				return this._HouseRent;
			}
			set
			{
				if ((this._HouseRent != value))
				{
					this.OnHouseRentChanging(value);
					this.SendPropertyChanging();
					this._HouseRent = value;
					this.SendPropertyChanged("HouseRent");
					this.OnHouseRentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicalSupport", DbType="Int")]
		public System.Nullable<int> MedicalSupport
		{
			get
			{
				return this._MedicalSupport;
			}
			set
			{
				if ((this._MedicalSupport != value))
				{
					this.OnMedicalSupportChanging(value);
					this.SendPropertyChanging();
					this._MedicalSupport = value;
					this.SendPropertyChanged("MedicalSupport");
					this.OnMedicalSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConvanceSupport", DbType="Int")]
		public System.Nullable<int> ConvanceSupport
		{
			get
			{
				return this._ConvanceSupport;
			}
			set
			{
				if ((this._ConvanceSupport != value))
				{
					this.OnConvanceSupportChanging(value);
					this.SendPropertyChanging();
					this._ConvanceSupport = value;
					this.SendPropertyChanged("ConvanceSupport");
					this.OnConvanceSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoodSupport", DbType="Int")]
		public System.Nullable<int> FoodSupport
		{
			get
			{
				return this._FoodSupport;
			}
			set
			{
				if ((this._FoodSupport != value))
				{
					this.OnFoodSupportChanging(value);
					this.SendPropertyChanging();
					this._FoodSupport = value;
					this.SendPropertyChanged("FoodSupport");
					this.OnFoodSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverTimeRate", DbType="Float")]
		public System.Nullable<double> OverTimeRate
		{
			get
			{
				return this._OverTimeRate;
			}
			set
			{
				if ((this._OverTimeRate != value))
				{
					this.OnOverTimeRateChanging(value);
					this.SendPropertyChanging();
					this._OverTimeRate = value;
					this.SendPropertyChanged("OverTimeRate");
					this.OnOverTimeRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoiningDate", DbType="Date")]
		public System.Nullable<System.DateTime> JoiningDate
		{
			get
			{
				return this._JoiningDate;
			}
			set
			{
				if ((this._JoiningDate != value))
				{
					this.OnJoiningDateChanging(value);
					this.SendPropertyChanging();
					this._JoiningDate = value;
					this.SendPropertyChanged("JoiningDate");
					this.OnJoiningDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoiningDateBangla", DbType="NChar(100)")]
		public string JoiningDateBangla
		{
			get
			{
				return this._JoiningDateBangla;
			}
			set
			{
				if ((this._JoiningDateBangla != value))
				{
					this.OnJoiningDateBanglaChanging(value);
					this.SendPropertyChanging();
					this._JoiningDateBangla = value;
					this.SendPropertyChanged("JoiningDateBangla");
					this.OnJoiningDateBanglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineId", DbType="Int")]
		public System.Nullable<int> LineId
		{
			get
			{
				return this._LineId;
			}
			set
			{
				if ((this._LineId != value))
				{
					this.OnLineIdChanging(value);
					this.SendPropertyChanging();
					this._LineId = value;
					this.SendPropertyChanged("LineId");
					this.OnLineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatagoryId", DbType="Int")]
		public System.Nullable<int> CatagoryId
		{
			get
			{
				return this._CatagoryId;
			}
			set
			{
				if ((this._CatagoryId != value))
				{
					this.OnCatagoryIdChanging(value);
					this.SendPropertyChanging();
					this._CatagoryId = value;
					this.SendPropertyChanged("CatagoryId");
					this.OnCatagoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryOrDate", DbType="Date")]
		public System.Nullable<System.DateTime> EntryOrDate
		{
			get
			{
				return this._EntryOrDate;
			}
			set
			{
				if ((this._EntryOrDate != value))
				{
					this.OnEntryOrDateChanging(value);
					this.SendPropertyChanging();
					this._EntryOrDate = value;
					this.SendPropertyChanged("EntryOrDate");
					this.OnEntryOrDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ProductionDeleteHistory")]
	public partial class tbl_ProductionDeleteHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _EmpId;
		
		private System.Nullable<int> _ProductId;
		
		private System.Nullable<System.DateTime> _ProductionDate;
		
		private System.Nullable<decimal> _Rate;
		
		private System.Nullable<double> _Qty;
		
		private System.Nullable<decimal> _Taka;
		
		private string _DeleteBy;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnEmpIdChanging(string value);
    partial void OnEmpIdChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnProductionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProductionDateChanged();
    partial void OnRateChanging(System.Nullable<decimal> value);
    partial void OnRateChanged();
    partial void OnQtyChanging(System.Nullable<double> value);
    partial void OnQtyChanged();
    partial void OnTakaChanging(System.Nullable<decimal> value);
    partial void OnTakaChanged();
    partial void OnDeleteByChanging(string value);
    partial void OnDeleteByChanged();
    partial void OnDeleteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeleteDateChanged();
    #endregion
		
		public tbl_ProductionDeleteHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", DbType="VarChar(50)")]
		public string EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this.OnEmpIdChanging(value);
					this.SendPropertyChanging();
					this._EmpId = value;
					this.SendPropertyChanged("EmpId");
					this.OnEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionDate", DbType="Date")]
		public System.Nullable<System.DateTime> ProductionDate
		{
			get
			{
				return this._ProductionDate;
			}
			set
			{
				if ((this._ProductionDate != value))
				{
					this.OnProductionDateChanging(value);
					this.SendPropertyChanging();
					this._ProductionDate = value;
					this.SendPropertyChanged("ProductionDate");
					this.OnProductionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Float")]
		public System.Nullable<double> Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taka", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Taka
		{
			get
			{
				return this._Taka;
			}
			set
			{
				if ((this._Taka != value))
				{
					this.OnTakaChanging(value);
					this.SendPropertyChanging();
					this._Taka = value;
					this.SendPropertyChanged("Taka");
					this.OnTakaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="VarChar(50)")]
		public string DeleteBy
		{
			get
			{
				return this._DeleteBy;
			}
			set
			{
				if ((this._DeleteBy != value))
				{
					this.OnDeleteByChanging(value);
					this.SendPropertyChanging();
					this._DeleteBy = value;
					this.SendPropertyChanged("DeleteBy");
					this.OnDeleteByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="Date")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this.OnDeleteDateChanging(value);
					this.SendPropertyChanging();
					this._DeleteDate = value;
					this.SendPropertyChanged("DeleteDate");
					this.OnDeleteDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ProductionInfo")]
	public partial class tbl_ProductionInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<System.DateTime> _ProductionDate;
		
		private string _EmpId;
		
		private System.Nullable<int> _ProductId;
		
		private System.Nullable<double> _Quantity;
		
		private System.Nullable<decimal> _Rate;
		
		private System.Nullable<decimal> _TotalRate;
		
		private System.Nullable<System.DateTime> _InputDate;
		
		private string _InputBy;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _UpdateBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnProductionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnProductionDateChanged();
    partial void OnEmpIdChanging(string value);
    partial void OnEmpIdChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnQuantityChanging(System.Nullable<double> value);
    partial void OnQuantityChanged();
    partial void OnRateChanging(System.Nullable<decimal> value);
    partial void OnRateChanged();
    partial void OnTotalRateChanging(System.Nullable<decimal> value);
    partial void OnTotalRateChanged();
    partial void OnInputDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInputDateChanged();
    partial void OnInputByChanging(string value);
    partial void OnInputByChanged();
    partial void OnUpdateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateByChanging(string value);
    partial void OnUpdateByChanged();
    #endregion
		
		public tbl_ProductionInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductionDate", DbType="Date")]
		public System.Nullable<System.DateTime> ProductionDate
		{
			get
			{
				return this._ProductionDate;
			}
			set
			{
				if ((this._ProductionDate != value))
				{
					this.OnProductionDateChanging(value);
					this.SendPropertyChanging();
					this._ProductionDate = value;
					this.SendPropertyChanged("ProductionDate");
					this.OnProductionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpId", DbType="VarChar(50)")]
		public string EmpId
		{
			get
			{
				return this._EmpId;
			}
			set
			{
				if ((this._EmpId != value))
				{
					this.OnEmpIdChanging(value);
					this.SendPropertyChanging();
					this._EmpId = value;
					this.SendPropertyChanged("EmpId");
					this.OnEmpIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalRate", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TotalRate
		{
			get
			{
				return this._TotalRate;
			}
			set
			{
				if ((this._TotalRate != value))
				{
					this.OnTotalRateChanging(value);
					this.SendPropertyChanging();
					this._TotalRate = value;
					this.SendPropertyChanged("TotalRate");
					this.OnTotalRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputDate", DbType="Date")]
		public System.Nullable<System.DateTime> InputDate
		{
			get
			{
				return this._InputDate;
			}
			set
			{
				if ((this._InputDate != value))
				{
					this.OnInputDateChanging(value);
					this.SendPropertyChanging();
					this._InputDate = value;
					this.SendPropertyChanged("InputDate");
					this.OnInputDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputBy", DbType="VarChar(50)")]
		public string InputBy
		{
			get
			{
				return this._InputBy;
			}
			set
			{
				if ((this._InputBy != value))
				{
					this.OnInputByChanging(value);
					this.SendPropertyChanging();
					this._InputBy = value;
					this.SendPropertyChanged("InputBy");
					this.OnInputByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="Date")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="VarChar(50)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this.OnUpdateByChanging(value);
					this.SendPropertyChanging();
					this._UpdateBy = value;
					this.SendPropertyChanged("UpdateBy");
					this.OnUpdateByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ProductName")]
	public partial class tbl_ProductName : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ProdectName;
		
		private System.Nullable<int> _ProductTypeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProdectNameChanging(string value);
    partial void OnProdectNameChanged();
    partial void OnProductTypeIdChanging(System.Nullable<int> value);
    partial void OnProductTypeIdChanged();
    #endregion
		
		public tbl_ProductName()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdectName", DbType="VarChar(50)")]
		public string ProdectName
		{
			get
			{
				return this._ProdectName;
			}
			set
			{
				if ((this._ProdectName != value))
				{
					this.OnProdectNameChanging(value);
					this.SendPropertyChanging();
					this._ProdectName = value;
					this.SendPropertyChanged("ProdectName");
					this.OnProdectNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeId", DbType="Int")]
		public System.Nullable<int> ProductTypeId
		{
			get
			{
				return this._ProductTypeId;
			}
			set
			{
				if ((this._ProductTypeId != value))
				{
					this.OnProductTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ProductTypeId = value;
					this.SendPropertyChanged("ProductTypeId");
					this.OnProductTypeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ProductSize")]
	public partial class tbl_ProductSize : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ProductSize;
		
		private System.Nullable<decimal> _Rate;
		
		private System.Nullable<int> _ProductNameId;
		
		private System.Nullable<int> _ProductTypeId;
		
		private string _FullProductName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProductSizeChanging(string value);
    partial void OnProductSizeChanged();
    partial void OnRateChanging(System.Nullable<decimal> value);
    partial void OnRateChanged();
    partial void OnProductNameIdChanging(System.Nullable<int> value);
    partial void OnProductNameIdChanged();
    partial void OnProductTypeIdChanging(System.Nullable<int> value);
    partial void OnProductTypeIdChanged();
    partial void OnFullProductNameChanging(string value);
    partial void OnFullProductNameChanged();
    #endregion
		
		public tbl_ProductSize()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductSize", DbType="VarChar(50)")]
		public string ProductSize
		{
			get
			{
				return this._ProductSize;
			}
			set
			{
				if ((this._ProductSize != value))
				{
					this.OnProductSizeChanging(value);
					this.SendPropertyChanging();
					this._ProductSize = value;
					this.SendPropertyChanged("ProductSize");
					this.OnProductSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductNameId", DbType="Int")]
		public System.Nullable<int> ProductNameId
		{
			get
			{
				return this._ProductNameId;
			}
			set
			{
				if ((this._ProductNameId != value))
				{
					this.OnProductNameIdChanging(value);
					this.SendPropertyChanging();
					this._ProductNameId = value;
					this.SendPropertyChanged("ProductNameId");
					this.OnProductNameIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeId", DbType="Int")]
		public System.Nullable<int> ProductTypeId
		{
			get
			{
				return this._ProductTypeId;
			}
			set
			{
				if ((this._ProductTypeId != value))
				{
					this.OnProductTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ProductTypeId = value;
					this.SendPropertyChanged("ProductTypeId");
					this.OnProductTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullProductName", DbType="VarChar(100)")]
		public string FullProductName
		{
			get
			{
				return this._FullProductName;
			}
			set
			{
				if ((this._FullProductName != value))
				{
					this.OnFullProductNameChanging(value);
					this.SendPropertyChanging();
					this._FullProductName = value;
					this.SendPropertyChanged("FullProductName");
					this.OnFullProductNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ProductType")]
	public partial class tbl_ProductType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductId;
		
		private string _ProductType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIdChanging(int value);
    partial void OnProductIdChanged();
    partial void OnProductTypeChanging(string value);
    partial void OnProductTypeChanged();
    #endregion
		
		public tbl_ProductType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductType", DbType="VarChar(50)")]
		public string ProductType
		{
			get
			{
				return this._ProductType;
			}
			set
			{
				if ((this._ProductType != value))
				{
					this.OnProductTypeChanging(value);
					this.SendPropertyChanging();
					this._ProductType = value;
					this.SendPropertyChanged("ProductType");
					this.OnProductTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Stock")]
	public partial class tbl_Stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<int> _ProductId;
		
		private System.Nullable<double> _Quantity;
		
		private System.Nullable<decimal> _Price;
		
		private string _Location;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnQuantityChanging(System.Nullable<double> value);
    partial void OnQuantityChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    #endregion
		
		public tbl_Stock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
