<?xml version="1.0" encoding="utf-8"?><Database Name="DevERP" Class="DevERPDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=DevERP;Integrated Security=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Connection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_DailyStock" Member="tbl_DailyStocks">
    <Type Name="tbl_DailyStock">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecordDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreviousQuantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DailyProduction" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DailySell" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BalanceQty" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_EmployeeEntry" Member="tbl_EmployeeEntries">
    <Type Name="tbl_EmployeeEntry">
      <Column Name="EmpId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeIdBangla" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DesignationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstNameBangla" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Column Name="LastNameBangla" Type="System.String" DbType="NChar(500)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdditionalId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MotherName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PlaceOfBirth" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NationalIdCardNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NationalIdCardNoBangla" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
      <Column Name="Religion" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Hobbies" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MaritialStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MarriageDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PresentAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParmanentAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParmanentAddressBangla" Type="System.String" DbType="NChar(1000)" CanBeNull="true" />
      <Column Name="OfficialPhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PersonalPhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="OfficialEmail" Type="System.String" DbType="VarChar(320)" CanBeNull="true" />
      <Column Name="PersonalEmail" Type="System.String" DbType="VarChar(320)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttendenceCardId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AttendenceCardIdBangla" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="FingerPrintId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmployeePicture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DigitalSignature" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GrossSalary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BasicSalary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HouseRent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MedicalSupport" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConvanceSupport" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FoodSupport" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverTimeRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="JoiningDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="JoiningDateBangla" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="LineId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatagoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EntryOrDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductionDeleteHistory" Member="tbl_ProductionDeleteHistories">
    <Type Name="tbl_ProductionDeleteHistory">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Qty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Taka" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DeleteBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductionInfo" Member="tbl_ProductionInfos">
    <Type Name="tbl_ProductionInfo">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EmpId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalRate" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="InputDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InputBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductName" Member="tbl_ProductNames">
    <Type Name="tbl_ProductName">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProdectName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductType" Member="tbl_ProductTypes">
    <Type Name="tbl_ProductType">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Stock" Member="tbl_Stocks">
    <Type Name="tbl_Stock">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductSize" Member="tbl_ProductSizes">
    <Type Name="tbl_ProductSize">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductSize" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ProductNameId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullProductName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SalesPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ProductType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Party_tbl" Member="Party_tbls">
    <Type Name="Party_tbl">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PartyType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PartyId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrganizationName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactPersonName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OpeningBalance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BankInformation_tbl" Member="BankInformation_tbls">
    <Type Name="BankInformation_tbl">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VarBankid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VarBankName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="VarBankAddress" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="VarBankCityid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VarBankphoneno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VarEmailAddress" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="VarContractpersons" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VarWebAddress" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
      <Column Name="VarPicturePath" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="VarRemarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="VarBranchId" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CardCom" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemSales" Member="ItemSales">
    <Type Name="ItemSale">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VarSalesInvoNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DatSalesDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="VarCustomerId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VarSalesType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VarChequeNo" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="DatChequeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChequeAmt" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="VarChequeBankid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VarDepositBankId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="InvTotal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="InvDisAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NetPayAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CashRcvAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DuesAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="VarRemarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SoldBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VarApproval" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="VarApprovalBay" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateApprovalDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateApprovalTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TR" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemSalesDetails" Member="ItemSalesDetails">
    <Type Name="ItemSalesDetail">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VarSalesInvoNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VarItemCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FltItemQty" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ItemPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ATR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemSalesCollection" Member="ItemSalesCollections">
    <Type Name="ItemSalesCollection">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VarCollectionNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="VarCustomeId" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="varSalesOrderNo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DatCollectiondate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FltCollectionAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FltCollectionType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VarBankid" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="VarBankAccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VarChequeNo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DatChequeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="VarBankIdFrom" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CollectionBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AppCollection" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AppCollectionBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DatAppCollectionDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DatAppCollectionTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DailyWait" Member="DailyWaits">
    <Type Name="DailyWait">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RefNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HitDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AMT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Mrk" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="VarUsr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EntryTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Voucher" Member="Vouchers">
    <Type Name="Voucher">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="VoucherNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DebitAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreditAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPartsInfo" Member="tblPartsInfos">
    <Type Name="tblPartsInfo">
      <Column Name="PartsCode" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PartsName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsesLoc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PartsType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UsesPurpose" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ReOrderLevel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TenRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LifeCycle" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPayment" Member="tblPayments">
    <Type Name="tblPayment">
      <Column Name="PayInvoiceNo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PayDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SupplierId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PayType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChequeNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChequeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PayAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EntryBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EntryIp" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Approve" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ApproveBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPurchase" Member="tblPurchases">
    <Type Name="tblPurchase">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurchaseInvNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SupplierId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChalanNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="EntryBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Approve" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ApproveBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPurchaseDetails" Member="tblPurchaseDetails">
    <Type Name="tblPurchaseDetail">
      <Column Name="PDId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurchaseInvNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PartsCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblReturn" Member="tblReturns">
    <Type Name="tblReturn">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurchaseInvNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SupplierId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChalanNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="EntryBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Approve" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ApproveBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ApproveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblReturnDetails" Member="tblReturnDetails">
    <Type Name="tblReturnDetail">
      <Column Name="PDId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurchaseInvNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PartsCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSuppliers" Member="tblSuppliers">
    <Type Name="tblSupplier">
      <Column Name="SupplierId" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrganizationName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="OpeningBalance" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SupplierPic" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblCategory" Member="tblCategories">
    <Type Name="tblCategory">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblGroup" Member="tblGroups">
    <Type Name="tblGroup">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TempLedger" Member="TempLedgers">
    <Type Name="TempLedger">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HeadsName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="VoucherNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Debit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TempLedgerFinal" Member="TempLedgerFinals">
    <Type Name="TempLedgerFinal">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FDatDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FHeadsName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FVoucherNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FDescription" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FDebit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FCredit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FBalance" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>